### ISSUE TITLE
python3: src/hostapi/alsa/pa_linux_alsa.c:3641: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed.

### ISSUE THREAD

**Issue by antiochtech** [PortAudio/portaudio#405]
rpi 3b, raspbian buster

error occurs within a minute or two.

doesnt matter if im installing pyaudio and portaudio from packages or building them myself. ive tried the last stable release of pa, as well as the nightly build.

https://pastebin.com/id2QaedQ

[Edit: Reproducing example at above link is
```
#!/usr/bin/env python3
 
import sys
import pyaudio
import time
import RPi.GPIO as GPIO
from array import array
 
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(24, GPIO.OUT)
 
THRESHOLD = 327
MAX_SILENCE = 62
CHUNK_SIZE = 1024
FORMAT = pyaudio.paInt16
RATE = 44100
 
def is_silent(snd_data):
    "Returns 'True' if below the 'silent' threshold"
    return max(snd_data) < THRESHOLD
 
def listen():
    num_silent = 0
    snd_started = False
 
    while True:
        # little endian, signed short
        snd_data = array('h', stream.read(CHUNK_SIZE))
        if sys.byteorder == 'big':
            snd_data.byteswap()
 
        silent = is_silent(snd_data)
 
        if silent:
            if snd_started:
                num_silent += 1
                GPIO.output(24,0)
                sys.stdout.write("data: yellow\n\n")
            elif not snd_started:
                GPIO.output(24,1)
                sys.stdout.write("data: red\n\n")
            sys.stdout.flush()
        elif not silent:
            if snd_started:
                num_silent = 0
            elif not snd_started:
                snd_started = True
            GPIO.output(24,0)
            sys.stdout.write("data: green\n\n")
            sys.stdout.flush()
 
        if snd_started and num_silent > MAX_SILENCE:
            snd_started = False
            num_silent = 0
            sys.stdout.write("data: red\n\n")
            sys.stdout.flush()
            GPIO.output(24,0)
 
        if snd_started and silent and num_silent < MAX_SILENCE:
            GPIO.output(24,1)
 
if __name__ == '__main__':
    p = pyaudio.PyAudio()
    stream = p.open(format=FORMAT, channels=1, rate=RATE,
    input=True, output=True,
    frames_per_buffer=CHUNK_SIZE)
    sys.stdout.write('Content-type: text/event-stream \r\n\r\n')
    listen()
    stream.stop_stream()
    stream.close()
    p.terminate()
```

**Comment by RossBencina** [comment]
Looks like a duplicate of #271 and possibly #268

**Comment by RossBencina** [comment]
@antiochtech are you able to try the latest nightly snapshot of PortAudio, this was probably fixed by PR #344 10 days ago.

**Comment by antiochtech** [comment]
> @antiochtech are you able to try the latest nightly snapshot of PortAudio, this was probably fixed by PR #344 10 days ago.

yes, just tried it today.

**Comment by antiochtech** [comment]
sorry, false alarm (dumb n00b mistake). didnt realize raspbian comes with libportaudio2 which is still contains the bug. i mistakenly thought by not having libportaudio-dev that i was without a pre-existing version.
`sudo apt remove libportaudio2`
followed by building pyaudio made me feel the joy.

**Comment by jaded0** [comment]
This issue is still occurring on version portaudio19-dev (19.6.0-1build1) on ubuntu Ubuntu 22.04.2 LTS, using pyaudio 0.2.13

**Comment by RossBencina** [comment]
@jaded0 have you tried 19.7.0 or our development head?
